Upgrade Scala versions, plugins and dependencies
pjan/akka-d3 pull request #24
Opened 2018-01-22 01:50 UTC by stefansperber

2018-01-22 01:56 UTC, stefansperber commented on akka-d3-readside-cassandra/src/main/resources/reference.conf
> +  # FQCN of the cassandra journal plugin
@pjan I copied the `cassandra-journal` section from `akka-persistence-cassandra`'s reference configuration in the `cassandra-readside` section so we can see easily what changed between versions. Let me know what to add/rewrite/take out.

(There are also `cassandra-snapshot-store` and `cassandra-query-journal` sections in the `akka-persistence-cassandra` reference configuration; I didn't add them here.)

https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/resources/reference.conf#L15

2018-02-01 06:21 UTC, pjan requested changes

2018-02-01 06:21 UTC, pjan commented on build.sbt
> +    D.simulacrum,
I think we can completely drop these dependencies. Are not being used anywhere

2018-02-01 06:21 UTC, pjan commented on build.sbt
> +    val machinist                = "0.6.3"
remove this and the next one from the list here?

2018-02-01 07:25 UTC, pjan approved these changes

2018-02-01 07:25 UTC, merged